version: '3.5'
services: # Contenedores

    maestro1:
        image: elasticsearch:7.9.3
        container_name: maestro1
        environment:
            - node.name=maestro1
            - cluster.name=MiCluster
            - cluster.initial_master_nodes=maestro1,maestro2
            - discovery.seed_hosts=maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=true
            - node.voting_only=false
            - node.data=false
            - node.ingest=false 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"
    maestro2:
        image: elasticsearch:7.9.3
        container_name: maestro2
        environment:
            - node.name=maestro2
            - cluster.name=MiCluster
            - cluster.initial_master_nodes=maestro1,maestro2
            - discovery.seed_hosts=maestro1
            # Configuración de las tareas que puede hacer este nodo
            - node.master=true
            - node.voting_only=false
            - node.data=false
            - node.ingest=false 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"

    datos1:
        image: elasticsearch:7.9.3
        container_name: datos1
        environment:
            - node.name=datos1
            - cluster.name=MiCluster
            - discovery.seed_hosts=maestro1,maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=true
            - node.voting_only=true
            - node.data=true
            - node.ingest=false 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"
        
    datos2:
        image: elasticsearch:7.9.3
        container_name: datos2
        environment:
            - node.name=datos2
            - cluster.name=MiCluster
            - discovery.seed_hosts=maestro1,maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=false
            - node.data=true
            - node.ingest=false 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password        
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"
    
    datos3:
        image: elasticsearch:7.9.3
        container_name: datos3
        environment:
            - node.name=datos3
            - cluster.name=MiCluster
            - discovery.seed_hosts=maestro1,maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=false
            - node.data=true
            - node.ingest=false 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password        
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"
    
    datos4:
        image: elasticsearch:7.9.3
        container_name: datos4
        environment:
            - node.name=datos4
            - cluster.name=MiCluster
            - discovery.seed_hosts=maestro1,maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=false
            - node.data=true
            - node.ingest=false 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password        
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"
    
    ingesta1:
        image: elasticsearch:7.9.3
        container_name: ingesta1
        environment:
            - node.name=ingesta1
            - cluster.name=MiCluster
            - discovery.seed_hosts=maestro1,maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=false
            - node.data=false
            - node.ingest=true 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password        
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"
    
    ingesta2:
        image: elasticsearch:7.9.3
        container_name: ingesta2
        environment:
            - node.name=ingesta2
            - cluster.name=MiCluster
            - discovery.seed_hosts=maestro1,maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=false
            - node.data=false
            - node.ingest=true 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password        
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"

    coordinador1:
        image: elasticsearch:7.9.3
        container_name: coordinador1
        environment:
            - node.name=coordinador1
            - cluster.name=MiCluster
            - discovery.seed_hosts=maestro1,maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=false
            - node.data=false
            - node.ingest=false 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password        
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"
    
    coordinador2:
        image: elasticsearch:7.9.3
        container_name: coordinador2
        environment:
            - node.name=coordinador2
            - cluster.name=MiCluster
            - discovery.seed_hosts=maestro1,maestro2
            # Configuración de las tareas que puede hacer este nodo
            - node.master=false
            - node.data=false
            - node.ingest=false 
            # Para que no mire límites (85% y 90%) a la hora de poner shards
            - cluster.routing.allocation.disk.threshold_enabled=false
            # Seguridad
            - ELASTIC_PASSWORD=password        
            # Memoria RAM para el nodo 220 Mbs 
            - "ES_JAVA_OPTS=-Xms220m -Xmx220m"
        
    cerebro:
        image: lmenezes/cerebro:0.8.5
        container_name: cerebro
        ports:
            - 8081:9000

    kibana:
        image: kibana:7.9.3
        container_name: kibana
        ports:
            - 8082:5601
        environment:
            - ELASTICSEARCH_HOSTS=http://coordinador1:9200
